// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0--rc2
// source: api/proto/riftofog/game.proto

package riftofog

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 行为请求：网关或 gRPC 调用 Combat/Event/Resource 时传入。
type ActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionKey     string                 `protobuf:"bytes,1,opt,name=action_key,json=actionKey,proto3" json:"action_key,omitempty"` // 行为 key
	Str           int32                  `protobuf:"varint,2,opt,name=str,proto3" json:"str,omitempty"`
	IntVal        int32                  `protobuf:"varint,3,opt,name=int_val,json=intVal,proto3" json:"int_val,omitempty"`
	Lck           int32                  `protobuf:"varint,4,opt,name=lck,proto3" json:"lck,omitempty"`
	Stealth       int32                  `protobuf:"varint,5,opt,name=stealth,proto3" json:"stealth,omitempty"`
	Hp            int32                  `protobuf:"varint,6,opt,name=hp,proto3" json:"hp,omitempty"`
	Ap            int32                  `protobuf:"varint,7,opt,name=ap,proto3" json:"ap,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`                               // 当前状态，如"中毒 燃烧"
	EnemyType     string                 `protobuf:"bytes,9,opt,name=enemy_type,json=enemyType,proto3" json:"enemy_type,omitempty"`        // 仅 Combat 用：patrol/guard/swarm
	RoomContent   string                 `protobuf:"bytes,10,opt,name=room_content,json=roomContent,proto3" json:"room_content,omitempty"` // 仅 Event/Resource 用
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionRequest) Reset() {
	*x = ActionRequest{}
	mi := &file_api_proto_riftofog_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionRequest) ProtoMessage() {}

func (x *ActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_riftofog_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionRequest.ProtoReflect.Descriptor instead.
func (*ActionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_riftofog_game_proto_rawDescGZIP(), []int{0}
}

func (x *ActionRequest) GetActionKey() string {
	if x != nil {
		return x.ActionKey
	}
	return ""
}

func (x *ActionRequest) GetStr() int32 {
	if x != nil {
		return x.Str
	}
	return 0
}

func (x *ActionRequest) GetIntVal() int32 {
	if x != nil {
		return x.IntVal
	}
	return 0
}

func (x *ActionRequest) GetLck() int32 {
	if x != nil {
		return x.Lck
	}
	return 0
}

func (x *ActionRequest) GetStealth() int32 {
	if x != nil {
		return x.Stealth
	}
	return 0
}

func (x *ActionRequest) GetHp() int32 {
	if x != nil {
		return x.Hp
	}
	return 0
}

func (x *ActionRequest) GetAp() int32 {
	if x != nil {
		return x.Ap
	}
	return 0
}

func (x *ActionRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ActionRequest) GetEnemyType() string {
	if x != nil {
		return x.EnemyType
	}
	return ""
}

func (x *ActionRequest) GetRoomContent() string {
	if x != nil {
		return x.RoomContent
	}
	return ""
}

// 行为结果：HP/AP 变化已在服务端按「不低于 0」截断。
type ActionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ResultText    string                 `protobuf:"bytes,2,opt,name=result_text,json=resultText,proto3" json:"result_text,omitempty"` // 展示给玩家的描述
	HpDelta       int32                  `protobuf:"varint,3,opt,name=hp_delta,json=hpDelta,proto3" json:"hp_delta,omitempty"`
	ApDelta       int32                  `protobuf:"varint,4,opt,name=ap_delta,json=apDelta,proto3" json:"ap_delta,omitempty"`
	NewStatus     string                 `protobuf:"bytes,5,opt,name=new_status,json=newStatus,proto3" json:"new_status,omitempty"`       // 新增状态
	ClearStatus   string                 `protobuf:"bytes,6,opt,name=clear_status,json=clearStatus,proto3" json:"clear_status,omitempty"` // 清除状态
	Reward        string                 `protobuf:"bytes,7,opt,name=reward,proto3" json:"reward,omitempty"`                              // 获得的物品/信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResult) Reset() {
	*x = ActionResult{}
	mi := &file_api_proto_riftofog_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResult) ProtoMessage() {}

func (x *ActionResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_riftofog_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResult.ProtoReflect.Descriptor instead.
func (*ActionResult) Descriptor() ([]byte, []int) {
	return file_api_proto_riftofog_game_proto_rawDescGZIP(), []int{1}
}

func (x *ActionResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ActionResult) GetResultText() string {
	if x != nil {
		return x.ResultText
	}
	return ""
}

func (x *ActionResult) GetHpDelta() int32 {
	if x != nil {
		return x.HpDelta
	}
	return 0
}

func (x *ActionResult) GetApDelta() int32 {
	if x != nil {
		return x.ApDelta
	}
	return 0
}

func (x *ActionResult) GetNewStatus() string {
	if x != nil {
		return x.NewStatus
	}
	return ""
}

func (x *ActionResult) GetClearStatus() string {
	if x != nil {
		return x.ClearStatus
	}
	return ""
}

func (x *ActionResult) GetReward() string {
	if x != nil {
		return x.Reward
	}
	return ""
}

var File_api_proto_riftofog_game_proto protoreflect.FileDescriptor

const file_api_proto_riftofog_game_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/proto/riftofog/game.proto\x12\briftofog\"\xff\x01\n" +
	"\rActionRequest\x12\x1d\n" +
	"\n" +
	"action_key\x18\x01 \x01(\tR\tactionKey\x12\x10\n" +
	"\x03str\x18\x02 \x01(\x05R\x03str\x12\x17\n" +
	"\aint_val\x18\x03 \x01(\x05R\x06intVal\x12\x10\n" +
	"\x03lck\x18\x04 \x01(\x05R\x03lck\x12\x18\n" +
	"\astealth\x18\x05 \x01(\x05R\astealth\x12\x0e\n" +
	"\x02hp\x18\x06 \x01(\x05R\x02hp\x12\x0e\n" +
	"\x02ap\x18\a \x01(\x05R\x02ap\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"enemy_type\x18\t \x01(\tR\tenemyType\x12!\n" +
	"\froom_content\x18\n" +
	" \x01(\tR\vroomContent\"\xd9\x01\n" +
	"\fActionResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vresult_text\x18\x02 \x01(\tR\n" +
	"resultText\x12\x19\n" +
	"\bhp_delta\x18\x03 \x01(\x05R\ahpDelta\x12\x19\n" +
	"\bap_delta\x18\x04 \x01(\x05R\aapDelta\x12\x1d\n" +
	"\n" +
	"new_status\x18\x05 \x01(\tR\tnewStatus\x12!\n" +
	"\fclear_status\x18\x06 \x01(\tR\vclearStatus\x12\x16\n" +
	"\x06reward\x18\a \x01(\tR\x06reward2Q\n" +
	"\rCombatService\x12@\n" +
	"\rExecuteAction\x12\x17.riftofog.ActionRequest\x1a\x16.riftofog.ActionResult2P\n" +
	"\fEventService\x12@\n" +
	"\rExecuteAction\x12\x17.riftofog.ActionRequest\x1a\x16.riftofog.ActionResult2S\n" +
	"\x0fResourceService\x12@\n" +
	"\rExecuteAction\x12\x17.riftofog.ActionRequest\x1a\x16.riftofog.ActionResultB'Z%go-server/api/proto/riftofog;riftofogb\x06proto3"

var (
	file_api_proto_riftofog_game_proto_rawDescOnce sync.Once
	file_api_proto_riftofog_game_proto_rawDescData []byte
)

func file_api_proto_riftofog_game_proto_rawDescGZIP() []byte {
	file_api_proto_riftofog_game_proto_rawDescOnce.Do(func() {
		file_api_proto_riftofog_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_riftofog_game_proto_rawDesc), len(file_api_proto_riftofog_game_proto_rawDesc)))
	})
	return file_api_proto_riftofog_game_proto_rawDescData
}

var file_api_proto_riftofog_game_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_riftofog_game_proto_goTypes = []any{
	(*ActionRequest)(nil), // 0: riftofog.ActionRequest
	(*ActionResult)(nil),  // 1: riftofog.ActionResult
}
var file_api_proto_riftofog_game_proto_depIdxs = []int32{
	0, // 0: riftofog.CombatService.ExecuteAction:input_type -> riftofog.ActionRequest
	0, // 1: riftofog.EventService.ExecuteAction:input_type -> riftofog.ActionRequest
	0, // 2: riftofog.ResourceService.ExecuteAction:input_type -> riftofog.ActionRequest
	1, // 3: riftofog.CombatService.ExecuteAction:output_type -> riftofog.ActionResult
	1, // 4: riftofog.EventService.ExecuteAction:output_type -> riftofog.ActionResult
	1, // 5: riftofog.ResourceService.ExecuteAction:output_type -> riftofog.ActionResult
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_riftofog_game_proto_init() }
func file_api_proto_riftofog_game_proto_init() {
	if File_api_proto_riftofog_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_riftofog_game_proto_rawDesc), len(file_api_proto_riftofog_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_api_proto_riftofog_game_proto_goTypes,
		DependencyIndexes: file_api_proto_riftofog_game_proto_depIdxs,
		MessageInfos:      file_api_proto_riftofog_game_proto_msgTypes,
	}.Build()
	File_api_proto_riftofog_game_proto = out.File
	file_api_proto_riftofog_game_proto_goTypes = nil
	file_api_proto_riftofog_game_proto_depIdxs = nil
}
